# Generated by Django 4.0.5 on 2022-07-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('facility1', models.CharField(blank=True, max_length=30, null=True)),
                ('facility2', models.CharField(blank=True, max_length=30, null=True)),
                ('facility3', models.CharField(blank=True, max_length=30, null=True)),
                ('facility4', models.CharField(blank=True, max_length=30, null=True)),
                ('facility5', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Stan', 'Standard'), ('StanT', 'Standard Twin'), ('Del', 'Deluxe'), ('DelT', 'Deluxe Twin')], max_length=30)),
                ('rate', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
                ('user', models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
